'\" t
.ig
Man page for tn5250.

Copyright (C) 1999 - 2001 Carey Evans.

You can redistribute and/or modify this document under the terms of 
the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option)
any later version.

This document is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
..
.TH TN5250 1 "30 Jul 2001"
.SH NAME
tn5250 \- an implementation of the 5250 telnet protocol
.SH SYNOPSIS
.B tn5250
.RI [\| OPTIONS \|]
.IR host [\|: port \|]
.br
.B xt5250
.RI [\| OPTIONS \|]
.RI [\| host [\|: port \|]\|]
.br
.B tn5250 \-version
.SH "DESCRIPTION"
.B tn5250
emulates IBM's 5250 compatible terminals to connect over TCP/IP to an
IBM AS/400.  The terminal emulation works on any local terminal
supported by curses, and provides 132x27 and full colour support where
possible.
.PP
.B tn5250
will connect to the given
.IR host 's
telnet port, or a different
.I port
if specified.  The host name may be preceded by a
.IR protocol :
which specifies either to use telnet to the host, if omitted or set to
.I telnet
or
.IR tn5250 ,
or to replay a session dumped using the
.B trace
option if set to
.IR debug .
.PP
An IBM 5250 terminal supports a number of special keys, and does a lot 
of processing itself before sending data to the host system.  Because
a standard ASCII terminal does not support all these keys,
.B tn5250
uses control sequences to perform the operations.
.PP
Named session support (with the
.B env.DEVNAME
option) is available for most versions of OS/400, but is only supplied
with V4R3 and later versions.  For V3R2, V3R7, V4R1 and V4R2, please
see informational APAR II10918.
.SH OPTIONS
.TP
.BI trace= FILE
Log all
.B tn5250
actions to
.IR tracefile .
This file will get very large, and may contain sensitive information
such as the password used to log in.
.TP
.BI map= CCSID
Set the translation table between ASCII and EBCDIC.  This should match
the CCSID of the interactive job.  The default for
.B tn5250
is
.BR 37 .
See
.B Translation Maps
below for more information.
.TP
.BI env.DEVNAME= NAME
Set the device name for the AS/400 to assign to the 5250 session.
This should be up to ten characters long and consist of only letters
and numbers.  It will be converted to uppercase and used as the name
of the 5250-compatible device on the AS/400.  There may only be one
session active with any given name at one time.
.TP
.BI env.TERM= TYPE
Set the terminal model name for the emulation session to use.  The
default depends on whether the terminal supports colour, and whether
it is large enough to support the large terminal size.  See
.B Display Types
below for valid model names.
.TP
.BI env. VARIABLE = VALUE
Set any other environment variables controlling the terminal session.
A list of relevant variables is given in section 5 of
.BR RFC2877 .
.TP
.B +/\-underscores
Force or disable the use of underscore characters instead of the underline
attribute, for terminals that do not support underlining but where
.B tn5250
does not work this out itself.
.TP
.B +/\-ruler
Turn the ruler feature on or off.  When enabled, the row and column of
the cursor will be highlighted.
.TP
.B \-version
Display the version of
.B tn5250
and exit.
.SH EXAMPLES
These are some examples of the use of
.BR tn5250 :
.TP
.I "tn5250 as400sys"
Connect to the system
.IR as400sys ,
using the default translation map (37)
and a generated session name
.RI (QPADEV #### ).
.TP
.I "tn5250 map=870 env.DEVNAME=session1 env.TERM=IBM-3477-FC as400sys"
Connect to
.I as400sys
using the translation map for CCSID 870 (Eastern Europe), the session
name SESSION1 and with a terminal supporting colour and a 132x27
display.
.SH USAGE
This manual assumes that the user is familiar with a real 5250
terminal, or another 5250 emulator, and only describes features
relevant to
.B tn5250
itself.
.SS "Keyboard Mapping"
The following table lists the 5250 functions implemented by
.BR tn5250 ,
and the corresponding keypresses.  Keys are represented as Emacs does:
.B C-a
means hold
.B Ctrl
and press
.BR A ,
.B M-a
means press
.B Esc
or
.B C-g
followed by
.BR A ,
and
.B C-M-a
means press
.B Esc
or
.B C-g
followed by
.BR C-a .
Most setups also let you use the
.B Alt
or
.B Meta
key for
.B M-
keypresses.
.PP
.TS
tab (@);
l l
__
lB l.
Function@Keypress
F1 - F10@f1 to f10, M-1 to M-
F11@f11 [1], M--
F12@f12 [1], M-=
F13 - F24@f13 to f24 [1], M-! to M-+
Enter@return, enter, C-j, C-m
Left@left
Right@right
Up@up
Down@down
Roll Up@next, pagedown, C-d, C-f
Roll Down@prev, pageup, C-b, C-u
Backspace@backspace [1]
Home@home, C-o
End@end
Insert@insert, M-i, M-delete
Delete@delete [1]
Reset@C-r, M-r
Print@C-p, M-p
Help@M-h
SysReq@C-c, M-s
Clear@M-c
FieldExit@C-k, M-x
TestReq@C-t
Toggle@M-t
Erase@C-e
Attn@C-a, M-a
Dup@M-d
Field+@C-x, + [2]
Field-@M-m, - [2]
NewLine@C-M-j
Next Field@tab, C-i
Prev Field@backtab [1]
_
Refresh@C-l, M-l
Quit@C-q
.TE
.IP [1]
Which keys generate f11-f24, backtab, backspace and delete is very
dependent on the configuration of the terminal.
.IP [2]
.B +
and
.B -
only work as Field+ and Field- in signed numeric fields.
.LP
.SS Display
The screen display tries to be the same as a colour 5250 terminal.
There are some unavoidable differences though:
.RS
.PP
ASCII terminals (and curses) do not support the 5250 column
separators.
.PP
Some terminals (mostly ones based on the VGA text mode) do not support
underlining.  If this is the case and
.B tn5250
does not detect it automatically, you should pass the
.B \-u
option.
.PP
Some terminals (such as
.BR xterm )
do not support blinking text.
.RE
.SS "Display Types"
The following values are valid for the terminal name option.
The default terminal, if none is specified, is selected from the first
listed below that supports both terminal size and colour support.
.PP
.TS
tab (@);
l l l
___
lB l lB.
Name@Description@Default
IBM-5555-C01@DBCS color (not supported)
IBM-5555-B01@DBCS monochrome (not supported)
IBM-3477-FC@27x132 color@Yes
IBM-3477-FG@27x132 monochrome@Yes
IBM-3180-2@27x132 monochrome
IBM-3179-2@24x80 color@Yes
IBM-3196-A1@24x80 monochrome
IBM-5292-2@24x80 color
IBM-5291-1@24x80 monochrome
IBM-5251-11@24x80 monochrome@Yes
.TE
.SS "Translation Maps"
CCSIDs on the AS/400 are listed in Appendix G of IBM manual
SC41-5101-01, AS/400 National Language Support.  This manual is
available on the web at
.RI < http://publib.boulder.ibm.com/cgi-bin/bookmgr/BOOKS/QB3AWC01/G.2 >.
.PP
Currently recognised values for the translation map are: 37, 256, 273,
277, 278, 280, 284, 285, 290, 297, 420, 424, 500, 870, 871, 875, 880, 905,
and 1026.  Most of these are translated to ISO-8859-1, also known as
Latin 1.  Some of them contain characters only present in another
encoding, which is used instead.  The valid CCSID values, and the Unix
encoding used, are listed below.
.PP
.TS
tab (:);
l l l
___
rB l l.
CCSID:Unix encoding:Description
37:ISO-8859-1:US, Canada, Netherlands,
::Portugal, Brazil, Australia,
::New Zealand
256:ISO-8859-1:Netherlands
273:ISO-8859-1:Austria, Germany
277:ISO-8859-1:Denmark, Norway
278:ISO-8859-1:Finland, Sweden
280:ISO-8859-1:Italy
284:ISO-8859-1:Spanish, Latin America
285:ISO-8859-1:United Kingdom
290:JIS_X0201:Katakana Extended
297:ISO-8859-1:France
420:ISO-8859-6:Arabic
424:ISO-8859-8:Hebrew
500:ISO-8859-1:Belgium, Canada, Switzerland
870:ISO-8859-2:Eastern Europe
871:ISO-8859-1:Iceland
875:ISO-8859-7:Greek
880:ISO-8859-5:Cyrillic
905:ISO-8859-3:Turkey \- Latin3
1026:ISO-8859-9:Turkey \- Latin5
.TE
.PP
If possible, configure your terminal to use the appropriate encoding
if your AS/400 uses any of these CCSIDs.
.SH BUGS
Please report any bugs you find to the bug tracker or to the linux5250
mailing list.  See the
.B tn5250
web site for more details.
.SH "SEE ALSO"
.BR lp5250d (1),
.BR http://tn5250.sourceforge.net/ ,
.BR RFC1205 ,
.BR RFC2877 ,
.BR II10918 .
.SH COPYRIGHT
.B tn5250
is copyright
.if t \(co
1997 \- 2001 Michael Madore.  This manpage is copyright
.if t \(co
1999 \- 2001 Carey Evans.
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.
.PP
You should have received a copy of the GNU Lesser General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.SH AUTHORS
.B tn5250
was written by Michael Madore, Jay Felice, Scott Klement
and others; see the AUTHORS file for details.
This manual page was written by Carey Evans.
