name: Build PR

on: pull_request

jobs:
  build-cmake:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set CMake Generator
      if: ${{ !startsWith(matrix.os, 'windows') }}
      run: |
        echo "{CMAKE_GENERATOR}={Ninja}" >> "$GITHUB_ENV"
    - name: CMake Build
      run: |
        cmake -B build-dir -S .
        cmake --build build-dir

  build-autoconf:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Autoconf Build
      run: |
        ./autogen.sh
        ./configure
        make -j
